### ISSUE TITLE
Node 12 is deprecated

### ISSUE THREAD

**Issue by simenandre** [JanneMattila/get-version-from-tag#1]
There might be time to bump this action to `node16`. 

> Node 12 has been out of support since [April 2022](https://github.com/nodejs/Release/#end-of-life-releases), as a result we have started the deprecation process of Node 12 for GitHub Actions. We plan to migrate all actions to run on Node16 by Summer 2023. We will monitor the progress of the migration and listen to the community for how things are going before we define a final date.
To raise awareness of the upcoming change, we are adding a warning into workflows which contain Actions running on Node 12. This will come into effect starting on September 27th.

Source: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

**Comment by donavanbecker** [comment]
@JanneMattila can we get this updated?

**Comment by JanneMattila** [comment]
Thanks to mentioning me @donavanbecker. I haven't see this issue before so sorry about that. Let me try to fix this.

**Comment by JanneMattila** [comment]
Thanks @simenandre and @donavanbecker !

**Comment by donavanbecker** [comment]
Thank you!!
