### ISSUE TITLE
Ignore folders in version tags.

### ISSUE THREAD

**Issue by SvenBunge** [JanneMattila/get-version-from-tag#4]
Please ignore the folder information and extract only the version.

Should: `release/v2024.10.0` ==> `2024.10.0`
Is: `releases/v2024.43.0`==> `releases/v2024.43.0`

**Comment by JanneMattila** [comment]
Great idea @SvenBunge! Let me look into that.

**Comment by JanneMattila** [comment]
@SvenBunge this should be now implemented in `v4`. Let me know if you have issues with it. Thanks for the idea!
